version: '3'


services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8855:80
    depends_on:
      - app
    container_name: qainar_nginx
    environment:
      PHP_IDE_CONFIG: serverName=qainar_docker
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: qainar_backend_app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PHP_IDE_CONFIG: serverName=qainar_docker
      DATABASE_URL: postgresql://localhost:5435/qainar_db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: qainar_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    container_name: qainar_db

  cloudbeaver:
    image: dbeaver/cloudbeaver
    depends_on:
      - db
    container_name: qainar_cloudbeaver
    restart: always
    ports:
      - '3523:8978'
    volumes:
      - ./cloudbeaver:/opt/cloudbeaver/workspace


